In [1]:
import numpy as np

In [4]:
arr1 =np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [8]:
np.ones((2,3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2) # Element-wise addition
print(arr1 - arr2) # Element-wise subtraction
print(arr1 * arr2) # Element-wise multiplication

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [15]:
#universal functions
arr1 = np.array([1, 2, 3])

print(np.sqrt(arr1)) # Square root

print(np.exp(arr1)) # Exponential

print(np.log(arr1)) # Natural logarithm

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
